config/routes.rb
Rails.application.routes.draw do
  devise_for :users
  resources :cats
  root to: "home#index"
  resources :users
  resources :cats do
    resource :favorites, only: [:create, :destroy]
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/cat.rb
class Cat < ApplicationRecord
  mount_uploader :image_id, ImageUploader
  belongs_to :user
  has_many :favorites, dependent: :destroy

  with_options presence: true do
    validates :catname
    validates :appeal_point
    validates :image_id
  end
end

app/models/favorite.rb
class Favorite < ApplicationRecord
  belongs_to :user
  belongs_to :cat

  validates_uniqueness_of :cat_id, scope: :user_id
end

app/models/user.rb
class User < ApplicationRecord
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  mount_uploader :profile_image_id, ImageUploader
  has_many :cats, dependent: :destroy
  has_many :favorites, dependent: :destroy

  validates :username, presence: true

  def already_favorited?(user)
    favorites.exists(user_id: user.id)
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  before_action :configure_permitted_parameters, if: :devise_controller?

  def after_sign_in_path_for(resource)
    user_path(@user.id)
  end

  private

  def configure_permitted_parameters
    devise_parameter_sanitizer.permit(:sign_up, keys: [:username])
  end
end

app/controllers/cats_controller.rb
class CatsController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @cats = Cat.all
  end

  def show
    @cat = Cat.find(params[:id])
  end

  def new
    @cat = Cat.new
  end

  def create
    @cat = current_user.cats.build(cat_params)
    if @cat.save
      redirect_to cat_path(@cat), notice: "投稿に成功しました。"
    else
      render :new
    end
  end

  def edit
    @cat = Cat.find(params[:id])
    if @cat.user != current_user
      redirect_to cats_path, alert: "不正なアクセスです。"
    end
  end

  def update
    @cat = Cat.find(params[:id])
    if @cat.update(cat_params)
      redirect_to cat_path(@cat), notice: 'データを更新しました。'
    else
      render :edit
    end
  end

  def destroy
    cat = Cat.find(params[:id])
    cat.destroy
    redirect_to cats_path(@cat), notice: 'データを削除しました。'
  end

  private

  def cat_params
    params.require(:cat).permit(:catname, :appeal_point, :image_id)
  end
end

app/controllers/favorites_controller.rb
class FavoritesController < ApplicationController
  def create
    @favorite = current_user.favorites.create(cat_id: params[:cat_id])
    redirect_back(fallback_location: root_path)
  end

  def destroy
    @cat = Cat.find(params[:cat_id])
    if (@favorite = current_user.favorites.find_by(cat_id: @cat.id)) == nil
      @favorite = current_user.favorites.create(cat_id: params[:cat_id])
      redirect_back(fallback_location: root_path)
    else
      @favorite = current_user.favorites.find_by(cat_id: @cat.id)
      @favorite.destroy
      redirect_back(fallback_location: root_path)
    end
  end
end

app/controllers/home_controller.rb
class HomeController < ApplicationController
  def index
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :authenticate_user!, except: [:index]
  def index
    @users = User.all
  end

  def show
    @user = User.find(params[:id])
  end

  def edit
    @user = User.find(params[:id])
    if @user != current_user
      redirect_to user_path(current_user), alert: "不正なアクセスです。"
    end
  end

  def update
    @user = User.find(params[:id])
    if @user.update(user_params)
      redirect_to user_path(@user), notice: "ユーザー情報を更新しました。"
    else
      render :edit
    end
  end

  private
  def user_params
    params.require(:user).permit(:username, :email, :profile, :profile_image_id)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/cats_helper.rb
module CatsHelper
  def button_text
    if action_name == "new"
      "登録する"
    elsif action_name == "edit"
      "更新する"
    end
  end
end

app/helpers/devise_helper.rb
module DeviseHelper
  def bootstrap_devise_error_messages!
    return "" if resource.errors.empty?

    html = ""
    resource.errors.full_messages.each do |error_message|
      html += <<-EOF
      <div class="alert alert-danger alert-dismissible" role="alert">
        <button type="button" class="close" data-dismiss="alert">
          <span aria-hidden="true">&times;</span>
          <span class="sr-only">close</span>
        </button>
        #{error_message}
      </div>
      EOF
    end
    html.html_safe
  end
end

app/helpers/favorites_helper.rb
module FavoritesHelper
end

app/helpers/home_helper.rb
module HomeHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/cats/_form.html.erb
      <% if @cat.errors.any? %>
        <div class="devise-sign-up-error">
          <h2><%= t("errors.template.header", model: Cat.model_name.human, count: @cat.errors.count) %></h2>
          <ul>
            <% @cat.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @cat do |f| %>
        <div class="form-group p-2 m-2">
          <%= f.label :catname %>
          <%= f.text_field :catname, class: "form-control" %>
        </div>

        <div class="form-group p-2 m-2">
          <%= f.label :appeal_point %>
          <%= f.text_field :appeal_point, class: "form-control" %>
        </div>

        <div class="form-group p-2 m-2">
          <%= f.label :image_id %>
          <%= f.file_field :image_id, class: "form-control" %>
        </div>

        <div class="form-group p-2 m-2">
          <%= f.button button_text, class: 'btn btn-warning' %>
          <%= link_to "戻る", :back , class: "btn btn-warning"%>
        </div>
      <% end %>

app/views/cats/edit.html.erb
<section>
  <div class="container ">
    <div class="row justify-content-center">
    <h2 class="section-title">にゃんこデータ編集</h2>
      <div class="regist_form">
        <%= render partial: "form", locals: { thing: @cat } %>
      </div>
    </div>
  </div>
</section>

app/views/cats/index.html.erb
<section>
  <div class="container">
    <h2 class="section-title">にゃんこデータ一覧</h2>
    <div class="card-box">
      <div class="card-container col df">
        <% @cats.each do |cat| %>
          <div class="card-item col-md-6 p-2">
            <div class="card">
              <div class="card-img">
                <%= link_to cat_path(cat) do %>
                  <img src='<%= cat.image_id %>' class="cat-img" alt="にゃんこ画像">
                <% end %>
              </div>
              <div class="card-body">
                <div class="card-content df-f gap20">
                  <div class="card-image">
                    <% if cat.user.profile_image_id? %>
                      <img src='<%= cat.user.profile_image_id %>' class="user-icon gap20" alt="ユーザー画像">
                    <% else %>
                      <div class="user-icon gap20">
                        <%= image_tag asset_path("default.png", alt: "ユーザー画像") %>
                      </div>
                    <% end %>
                  </div>
                  <div class="media-content">
                    <div class="title mt-10"><%=link_to cat.user.username, user_path(cat.user) %></div>
                  </div>
                  <div class="mt-10">
                    <% if user_signed_in? %>
                      <%= link_to cat_favorites_path(cat), method: :delete do %>
                          <i class="fas fa-heart"></i>
                      <% end %>
                    <% else %>
                      <%= link_to cat_favorites_path(cat), method: :post do %>
                          <i class="fas fa-heart"></i>
                      <% end %>
                    <% end %>
                    <%= cat.favorites.count %>
                  </div>
                </div>
                <div class="panel-block">
                  <%= cat.updated_at.strftime("%Y-%m-%d %H:%M") %>更新
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/cats/new.html.erb
<section>
  <div class="container ">
    <div class="row justify-content-center">
    <h2 class="section-title">新規にゃんこデータ作成</h2>
    <% if @cat.errors.any? %>
      <div class="alert alert-danger">
        <ul class="mb-0">
          <% @cat.errors.full_messages.each do |msg| %>
            <li><%= msg %></li>
          <% end %>
        </ul>
      </div>
    <% end %>
      <div class="regist_form">
        <%= render partial: "form", locals: { thing: @cat } %>
      </div>
    </div>
  </div>
</section>

app/views/cats/show.html.erb
<section>
  <div class="container ">
    <div class="row justify-content-center">
    <h2 class="section-title">にゃんこデータ詳細</h2>
      <div class="df">
        <div class="regist_form">
          <div class="card">
            <%= image_tag @cat.image_id.to_s %>
            <div class="card-body">
              <h4 class="card-title"><%= @cat.catname %></h4>
              <div class="content">
                <table class="table">
                  <tr>
                    <th>アピールポイント</th>
                  </tr>
                  <tr>
                    <td><%= simple_format @cat.appeal_point %></td>
                  </tr>
                </table>
                <div class="button-position">
                  <% if @cat.user_id == current_user.id %>
                    <div class="side-position">
                      <%= link_to "編集", edit_cat_path(@cat), class: "btn btn-warning" %>
                      <%= button_to "一覧へ戻る", { :action => "index" }, :method => "get", class: "btn btn-warning" %>
                    </div>
                    <div>
                      <%= link_to '削除', cat_path(@cat), method: :delete, data: {confirm: "投稿を削除します。よろしいですか？"},class: 'btn btn-danger' %>
                    </div>
                  <% end %>
                </div>
              </div>
            </div>
          </div>
        </div>
        <div class="regist_form">
          <div class="user-panel">
            <p class="user-panel-heading">
              撮影者 <%= @cat.user.username %>
            </p>
            <div class="user-panel-block">
              <p class="control">
                <%= @cat.user.profile %>
              </p>
            </div>
            <div class="user-panel-block2">
              <%= link_to user_path(@cat.user), class: "user-panel-block" do %>
                <%= @cat.user.username %> さんのページへ
              <% end %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

app/views/home/index.html.erb
<section>
  <h2 class="main-title"><span class="title-font">Catlog</span><br class="df">〜猫との思い出を撮りためよう！〜</h2>
  <div class="box3">
    <div class="box-inner">
      <div class="">
        <br>
        <%= link_to "ログイン", new_user_session_path, class: "btn btn-warning btn-width" %>
        <br>
        <%= link_to "新規登録", new_user_registration_path, class: "btn btn-warning btn-width" %>
      </div>
    </div>
  </div>
  <div class="main-img">
  <div>
</section>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
    <title>Catlog</title>
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <link rel="stylesheet" href="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/css/bootstrap.min.css" integrity="sha384-ggOyR0iXCbMQv3Xipma34MD+dH/1fQ784/j6cY/iJTQUOhcWr7x9JvoRxT2MZw1T" crossorigin="anonymous">
    <script src="https://kit.fontawesome.com/484e6509e8.js" crossorigin="anonymous"></script>
  </head>

  <body>
    <% if flash[:notice] %>
      <div class="devise-notice">
        <p class="notice"><%= notice %></p>
      </div>
    <% end %>

    <% if flash[:alert] %>
      <div class="devise-error">
        <p class="alert"><%= alert %></p>
      </div>
    <% end %>

    <nav class="navbar navbar-expand-lg navbar-light bg-warning">
      <div class="container">
      <% if user_signed_in? %>
        <a class="navbar-brand" href="/cats">Catlog</a>
      <% else %>
      <% flash[:alert] = "アカウント登録もしくはログインしてください。" %>
        <a class="navbar-brand" href="/users/sign_in">Catlog</a>
      <% end %>
      <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
        <span class="navbar-toggler-icon"></span>
      </button>

      <% if user_signed_in? %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active m-2 menu-bar-line">
              <%= link_to "にゃんこ情報一覧", cats_path, class: "link-color" %>
            </li>
            <li class="nav-item m-2 menu-bar-line">
              <%= link_to "にゃんこ情報投稿", new_cat_path, class: "link-color" %>
            </li>
            <li class="nav-item m-2 menu-bar-line">
              <%= link_to "猫グラファー一覧", users_path, class: "link-color" %>
            </li>
            <li class="nav-item m-2 menu-bar-line">
              <%= link_to "マイページ", user_path(current_user), class: "link-color" %>
            </li>
            <li class="nav-item dropdown m-2 menu-bar-line">
              <%= link_to "ログアウト", destroy_user_session_path, method: :delete, class: "link-color" %>
            </li>
          </ul>
        </div>
      <% else %>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
          <ul class="navbar-nav ml-auto">
            <li class="nav-item active m-2 menu-bar-line">
              <%= link_to "にゃんこ情報一覧", new_cat_path, class: "link-color" %>
            </li>
            <li class="nav-item m-2 menu-bar-line">
              <%= link_to "にゃんこ情報投稿", new_cat_path, class: "link-color" %>
            </li>
            <li class="nav-item dropdown m-2 menu-bar-line">
              <%= link_to "ログイン", new_user_session_path, class: "link-color" %>
            </li>
            <li class="nav-item dropdown m-2 menu-bar-line">
              <%= link_to "新規登録", new_user_registration_path, class: "link-color" %>
            </li>
          </ul>
        </div>
      <% end %>
    </nav>

    <%= yield %>
    <script src="https://code.jquery.com/jquery-3.3.1.slim.min.js" integrity="sha384-q8i/X+965DzO0rT7abK41JStQIAqVgRVzpbzo5smXKp4YfRvH+8abtTE1Pi6jizo" crossorigin="anonymous"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/popper.js/1.14.7/umd/popper.min.js" integrity="sha384-UO2eT0CpHqdSJQ6hJty5KVphtPhzWj9WO1clHTMGa3JDZwrnQq4sF86dIHNDz0W1" crossorigin="anonymous"></script>
    <script src="https://stackpath.bootstrapcdn.com/bootstrap/4.3.1/js/bootstrap.min.js" integrity="sha384-JjSmVgyd0p3pXB1rRibZUAYoIIy6OrQ6VrjIEaFf/nJGzIxFDsf4x0xIM+B07jRM" crossorigin="anonymous"></script>
  </body>
</html>

app/views/users/edit.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <h2 class="section-title">ユーザーデータ編集</h2>
      <div class="regist_form">
      <% if @user.errors.any? %>
        <div class="devise-sign-up-error">
          <h2><%= t("errors.template.header", model: User.model_name.human, count: @user.errors.count) %></h2>
          <ul>
            <% @user.errors.full_messages.each do |message| %>
            <li><%= message %></li>
            <% end %>
          </ul>
        </div>
      <% end %>
      <%= form_for @user do |f| %>
        <div class="form-group p-2 m-2">
          <%= f.label :username, "ユーザー名", class: "label" %>
          <%= f.text_field :username, class: "form-control" %>
        </div>

        <div class="form-group p-2 m-2">
          <%= f.label :email, "メールアドレス", class: "label" %>
          <%= f.email_field :email, class: "form-control" %>
        </div>

        <div class="form-group p-2 m-2">
          <%= f.label :profile, "プロフィール", class: "label" %>
          <%= f.text_area :profile, class: "form-control" %>
        </div>

        <div class="form-group p-2 m-2">
          <%= f.label :profile_image_id, "プロフィール画像", class: "label" %>
          <%= f.file_field :profile_image_id, class: "form-control" %>
        </div>

        <%= f.submit "更新", class: "btn btn-warning" %>
        <%= link_to "戻る", :back , class: "btn btn-warning"%>
      <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/index.html.erb
<section>
  <div class="container">
    <h2 class="section-title">猫グラファ一覧</h2>
    <div class="card-box">
      <div class="card-container col df">
        <% @users.each do |user| %>
          <div class="card-item col-md-6 p-2">
            <div class="card">
              <div class="card-content">
                <div class="card-image">
                  <%= link_to user_path(user) do %>
                    <% if user.profile_image_id? %>
                      <img src='<%= user.profile_image_id %>' class="icon" alt="ユーザー画像">
                    <% else %>
                      <%= image_tag asset_path("default.png", alt: "ユーザー画像") %>
                    <% end %>
                  <% end %>
                </div>
              </div>
              <div class="card-content">
                <div class="media">
                  <div class="media-content">
                    <div class="title"><%=link_to user.username, user_path(user) %></div>
                  </div>
                </div>
                <div class="content">
                  投稿数：<%= user.cats.count %>
                </div>
              </div>
            </div>
          </div>
        <% end %>
      </div>
    </div>
  </div>
</section>

app/views/users/show.html.erb
<section>
  <div class="container">
    <div class="row justify-content-center">
      <h2 class="section-title">マイページ</h2>
      <div class="regist_form df">
        <div>
          <% if @user.profile_image_id? %>
            <img src='<%= @user.profile_image_id %>' class="show-icon" alt="ユーザー画像">
          <% else %>
            <%= image_tag asset_path("default.png", alt: "ユーザー画像") %>
          <% end %>
        </div>
        <div>
          <table class="table">
            <tr>
              <td>
                <%= @user.username %>
              </td>
              <% if @user.id == current_user.id %>
              <td>
                <%= @user.email %>
              </td>
              <td class="change-prof-btn1">
                  <%= link_to "編集", edit_user_path(@user), class: "btn btn-warning" %>
              </td>
              <% end %>
              <td class="change-prof-btn1">
                <%= button_to "一覧へ戻る", { :action => "index" }, :method => "get", class: "btn btn-warning" %>
              </td>
            </tr>
          </table>
          <table class="table">
            <tr>
              <td>
                <%= @user.profile %>
              </td>
            </tr>
          </table>
          <div class="but-position">
            <% if @user.id == current_user.id %>
            <div class="change-prof-btn2">
                <%= link_to "編集", edit_user_path(@user), class: "btn btn-warning" %>
            </div>
            <% end %>
            <div class="change-prof-btn2">
              <%= button_to "一覧へ戻る", { :action => "index" }, :method => "get", class: "btn btn-warning" %>
            </div>
          </div>
        </div>
      </div>
    </div>
  </div>
</section>

<section>
  <div class="container">
    <h2 class="section-title">これまで撮ったにゃんこたち</h2>
    <div class="col df">
      <% @user.cats.each do |cat| %>
        <div class="card m-4">
          <div>
            <div class="user-cat-img">
              <%= link_to cat_path(cat) do %>
                <img src='<%= cat.image_id %>' class="cat-img" alt="にゃんこ画像">
              <% end %>
            </div>
          </div>
          <div class="user-cat-profile">
            <div class="media">
              <div class="cat-content">
                <%= link_to cat_path(cat), class: "panel-block" do %>
                  プロフィールはこちら！
                <% end %>
                <% if @user.id == current_user.id %>
                  <%= link_to edit_cat_path(cat), class: "panel-block" do %>
                    プロフィールの編集はこちら！
                  <% end %>
                  <%= link_to cat_path(cat), method: :delete, data: {confirm: "削除しますか？"}, class: "panel-block" do %>
                    プロフィールを削除はこちら！
                  <% end %>
                <% end %>
              </div>
            </div>
            <div class="panel-block">
              <%= cat.updated_at.strftime("%Y-%m-%d %H:%M") %>更新
            </div>
          </div>
        </div>
      <% end %>
    </div>
  </div>
</section>